import type { ThemeOption } from './types';

export const EBOOK_THEMES: ThemeOption[] = [
  {
    id: 'editorial',
    name: 'Warm Boho Business',
    description: 'Terracotta margins, sunflower stickers, arched frames, Playfair serifs, organic layouts.',
    bgColor: '#faf6f0',
    accentColor: '#c96f4a',
    textColor: '#3d2314',
    fontHeader: 'Playfair Display',
    fontBody: 'Cormorant Garamond',
    paletteColors: ['#faf6f0', '#e8b89a', '#c96f4a', '#3d2314'],
  },
  {
    id: 'wanderlust',
    name: 'Wanderlust Travel',
    description: 'Clean travel magazine — teal headings, landmark photography, two-column editorial spreads.',
    bgColor: '#f8fafb',
    accentColor: '#5ba4b4',
    textColor: '#1a2a32',
    fontHeader: 'Montserrat',
    fontBody: 'Inter',
    paletteColors: ['#f8fafb', '#b8d4dc', '#5ba4b4', '#1a2a32'],
  },
  {
    id: 'softpink',
    name: 'Soft Pink Editorial',
    description: 'Feminine lifestyle — dusty rose accents, serif headlines, white content islands on blush.',
    bgColor: '#fdf2f4',
    accentColor: '#c96b84',
    textColor: '#3d1f2a',
    fontHeader: 'Playfair Display',
    fontBody: 'Poppins',
    paletteColors: ['#fdf2f4', '#f5c6d0', '#c96b84', '#3d1f2a'],
  },
  {
    id: 'comic',
    name: 'Pop Art Comic',
    description: 'Bold pop-art comic book — magenta, orange, cyan blocks, halftone dots, thick outlines.',
    bgColor: '#ffffff',
    accentColor: '#e91e8c',
    textColor: '#1a1a1a',
    fontHeader: 'Anton',
    fontBody: 'Montserrat',
    paletteColors: ['#ffffff', '#ff6b35', '#e91e8c', '#00b4d8'],
  },
  {
    id: 'sporty',
    name: 'Sporty Editorial',
    description: 'High-energy sports magazine — deep maroon, vertical headings, action photos, thick borders.',
    bgColor: '#ffffff',
    accentColor: '#8b0026',
    textColor: '#121212',
    fontHeader: 'DM Serif Display',
    fontBody: 'Inter',
    paletteColors: ['#ffffff', '#e8e8e8', '#8b0026', '#121212'],
  },
  {
    id: 'wellness',
    name: 'Emocalm Wellness',
    description: 'Clean supplement brochure — botanical line art, color-coded tables, professional wellness.',
    bgColor: '#fafafa',
    accentColor: '#7c5295',
    textColor: '#2d2d2d',
    fontHeader: 'Montserrat',
    fontBody: 'Inter',
    paletteColors: ['#fafafa', '#c8e6c9', '#7c5295', '#e91e63'],
  },
  {
    id: 'newspaper',
    name: 'NYT Newspaper',
    description: 'Broadsheet editorial — multi-column serif text, pastel circle infographics, classic news feel.',
    bgColor: '#fffef8',
    accentColor: '#1a1a1a',
    textColor: '#1a1a1a',
    fontHeader: 'Lora',
    fontBody: 'Lora',
    paletteColors: ['#fffef8', '#fde68a', '#fbcfe8', '#1a1a1a'],
  },
  {
    id: 'botanical',
    name: 'Botanical Garden',
    description: 'Magazine style with sage green details, organic illustration frames, and classic layouts.',
    bgColor: '#edf0ea',
    accentColor: '#556b2f',
    textColor: '#1e291e',
    fontHeader: 'Cormorant Garamond',
    fontBody: 'Outfit',
    paletteColors: ['#edf0ea', '#a3b19b', '#556b2f', '#1e291e'],
  },
  {
    id: 'modern',
    name: 'Minimalist Business',
    description: 'Clean structured layouts, corporate blue accenting, precise borders, and clear columns.',
    bgColor: '#ffffff',
    accentColor: '#2563eb',
    textColor: '#0f172a',
    fontHeader: 'Montserrat',
    fontBody: 'Inter',
    paletteColors: ['#ffffff', '#f1f5f9', '#2563eb', '#0f172a'],
  },
  {
    id: 'noir',
    name: 'Midnight Noir',
    description: 'Mysterious dark theme featuring elegant gold borders, starry lighting, and high contrast.',
    bgColor: '#0d0e12',
    accentColor: '#d4af37',
    textColor: '#e2e8f0',
    fontHeader: 'Cinzel',
    fontBody: 'Playfair Display',
    paletteColors: ['#0d0e12', '#1e202b', '#d4af37', '#e2e8f0'],
  },
  {
    id: 'bloodred',
    name: 'Scarlet Editorial',
    description: 'High-end luxury editorial style — crimson accents, large translucent chapter numbers, and double column layouts.',
    bgColor: '#fdfbf7',
    accentColor: '#7a0b0d',
    textColor: '#2b0808',
    fontHeader: 'Playfair Display',
    fontBody: 'Lora',
    paletteColors: ['#5c0909', '#fdfbf7', '#7a0b0d', '#2b0808'],
  },
  {
    id: 'minimalblack',
    name: 'Minimal Black',
    description: 'Minimalist editorial — deep black and pure white contrast, elegant serif headlines, clean grid elements, and high-end modern layout structures.',
    bgColor: '#ffffff',
    accentColor: '#000000',
    textColor: '#1a1a1a',
    fontHeader: 'Playfair Display',
    fontBody: 'Inter',
    paletteColors: ['#000000', '#ffffff', '#e5e5e5', '#333333'],
  },
  {
    id: 'rose',
    name: 'Rose Editorial',
    description: 'Feminine, floral-accented design with deep burgundy details, elegant script headlines, and clean margins.',
    bgColor: '#fef9fa',
    accentColor: '#8a2846',
    textColor: '#2e1018',
    fontHeader: 'Dancing Script',
    fontBody: 'Poppins',
    paletteColors: ['#8a2846', '#f3d2c1', '#fef9fa', '#2e1018'],
  },
  {
    id: 'lavender',
    name: 'Lavender Fields',
    description: 'Serene lavender editorial — elegant serif headings, vertical labels, clean magazine columns, and funnel pages.',
    bgColor: '#f3f0f7',
    accentColor: '#5c3d91',
    textColor: '#1f1633',
    fontHeader: 'Cormorant Garamond',
    fontBody: 'Outfit',
    paletteColors: ['#5c3d91', '#b39ddb', '#f3f0f7', '#1f1633'],
  },
  {
    id: 'bolddark',
    name: 'Bold Dark Grid',
    description: 'Stark high-contrast layout — pure black theme, strong sans-serif titles, image grids, and pricing tables.',
    bgColor: '#000000',
    accentColor: '#ffffff',
    textColor: '#ffffff',
    fontHeader: 'Montserrat',
    fontBody: 'Inter',
    paletteColors: ['#000000', '#ffffff', '#262626', '#a3a3a3'],
  },
];
