import type { ThemeOption } from './types';

export const EBOOK_THEMES: ThemeOption[] = [
  {
    id: 'editorial',
    name: 'Warm Boho Business',
    description: 'Terracotta margins, sunflower stickers, arched frames, Playfair serifs, organic layouts.',
    bgColor: '#faf6f0',
    accentColor: '#c96f4a',
    textColor: '#3d2314',
    fontHeader: 'Playfair Display',
    fontBody: 'Cormorant Garamond',
    paletteColors: ['#faf6f0', '#e8b89a', '#c96f4a', '#3d2314'],
  },
  {
    id: 'wanderlust',
    name: 'Wanderlust Travel',
    description: 'Clean travel magazine — teal headings, landmark photography, two-column editorial spreads.',
    bgColor: '#f8fafb',
    accentColor: '#5ba4b4',
    textColor: '#1a2a32',
    fontHeader: 'Montserrat',
    fontBody: 'Inter',
    paletteColors: ['#f8fafb', '#b8d4dc', '#5ba4b4', '#1a2a32'],
  },
  {
    id: 'softpink',
    name: 'Soft Pink Editorial',
    description: 'Feminine lifestyle — dusty rose accents, serif headlines, white content islands on blush.',
    bgColor: '#fdf2f4',
    accentColor: '#c96b84',
    textColor: '#3d1f2a',
    fontHeader: 'Playfair Display',
    fontBody: 'Poppins',
    paletteColors: ['#fdf2f4', '#f5c6d0', '#c96b84', '#3d1f2a'],
  },
  {
    id: 'comic',
    name: 'Pop Art Comic',
    description: 'Bold pop-art comic book — magenta, orange, cyan blocks, halftone dots, thick outlines.',
    bgColor: '#ffffff',
    accentColor: '#e91e8c',
    textColor: '#1a1a1a',
    fontHeader: 'Anton',
    fontBody: 'Montserrat',
    paletteColors: ['#ffffff', '#ff6b35', '#e91e8c', '#00b4d8'],
  },
  {
    id: 'sporty',
    name: 'Sporty Editorial',
    description: 'High-energy sports magazine — deep maroon, vertical headings, action photos, thick borders.',
    bgColor: '#ffffff',
    accentColor: '#8b0026',
    textColor: '#121212',
    fontHeader: 'DM Serif Display',
    fontBody: 'Inter',
    paletteColors: ['#ffffff', '#e8e8e8', '#8b0026', '#121212'],
  },
  {
    id: 'wellness',
    name: 'Emocalm Wellness',
    description: 'Clean supplement brochure — botanical line art, color-coded tables, professional wellness.',
    bgColor: '#fafafa',
    accentColor: '#7c5295',
    textColor: '#2d2d2d',
    fontHeader: 'Montserrat',
    fontBody: 'Inter',
    paletteColors: ['#fafafa', '#c8e6c9', '#7c5295', '#e91e63'],
  },
  {
    id: 'construct',
    name: 'Constructivist Zine',
    description: 'Russian constructivism — bold red blocks, cream paper, oversized type, B&W photography.',
    bgColor: '#f5f2e9',
    accentColor: '#a51c1c',
    textColor: '#121212',
    fontHeader: 'Anton',
    fontBody: 'Montserrat',
    paletteColors: ['#f5f2e9', '#a51c1c', '#121212', '#ffffff'],
  },
  {
    id: 'newspaper',
    name: 'NYT Newspaper',
    description: 'Broadsheet editorial — multi-column serif text, pastel circle infographics, classic news feel.',
    bgColor: '#fffef8',
    accentColor: '#1a1a1a',
    textColor: '#1a1a1a',
    fontHeader: 'Lora',
    fontBody: 'Lora',
    paletteColors: ['#fffef8', '#fde68a', '#fbcfe8', '#1a1a1a'],
  },
  {
    id: 'botanical',
    name: 'Botanical Garden',
    description: 'Magazine style with sage green details, organic illustration frames, and classic layouts.',
    bgColor: '#edf0ea',
    accentColor: '#556b2f',
    textColor: '#1e291e',
    fontHeader: 'Cormorant Garamond',
    fontBody: 'Outfit',
    paletteColors: ['#edf0ea', '#a3b19b', '#556b2f', '#1e291e'],
  },
  {
    id: 'modern',
    name: 'Minimalist Business',
    description: 'Clean structured layouts, corporate blue accenting, precise borders, and clear columns.',
    bgColor: '#ffffff',
    accentColor: '#2563eb',
    textColor: '#0f172a',
    fontHeader: 'Montserrat',
    fontBody: 'Inter',
    paletteColors: ['#ffffff', '#f1f5f9', '#2563eb', '#0f172a'],
  },
  {
    id: 'noir',
    name: 'Midnight Noir',
    description: 'Mysterious dark theme featuring elegant gold borders, starry lighting, and high contrast.',
    bgColor: '#0d0e12',
    accentColor: '#d4af37',
    textColor: '#e2e8f0',
    fontHeader: 'Cinzel',
    fontBody: 'Playfair Display',
    paletteColors: ['#0d0e12', '#1e202b', '#d4af37', '#e2e8f0'],
  },
  {
    id: 'pinterest',
    name: 'Pinterest Classic',
    description: 'Aesthetic moodboards — soft beige, terracotta clay accents, drop caps, and arched steps layout.',
    bgColor: '#f4ece1',
    accentColor: '#caa27d',
    textColor: '#1a1a1a',
    fontHeader: 'Playfair Display',
    fontBody: 'Lora',
    paletteColors: ['#f4ece1', '#caa27d', '#1a1a1a', '#e8cbb6'],
  },
  {
    id: 'pinterest_teal',
    name: 'Pinterest Teal',
    description: 'Corporate business style — professional teal, dark navy blocks, clean slate pages, skyscraper graphics.',
    bgColor: '#f9fafb',
    accentColor: '#0d9488',
    textColor: '#111827',
    fontHeader: 'Montserrat',
    fontBody: 'Inter',
    paletteColors: ['#f9fafb', '#0d9488', '#111827', '#0f766e'],
  },
  {
    id: 'pinterest_pink',
    name: 'Pinterest Pink',
    description: 'Aesthetic rose lookbook — dusty rose accents, dark cherry text, polaroid photo frames, elegant borders.',
    bgColor: '#faf8f8',
    accentColor: '#b85a75',
    textColor: '#2d1a21',
    fontHeader: 'Playfair Display',
    fontBody: 'Lora',
    paletteColors: ['#faf8f8', '#b85a75', '#2d1a21', '#e8b8c4'],
  },
];
